services:
  postgres:
    image: postgres:16
    container_name: nebula-pgsql
    environment:
      POSTGRES_DB: nebuladb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: